# Copyright (c) 2026 NC Factory
# Author: NC MCU Factory Requirements Agent
# License: Apache-2.0
# Generated by: nc_socgen/scripts/gen_soc.py
# Generator version: 1.1.0
# Generation UTC: 2026-05-29T04:57:53.077343+00:00
# Source config: /tmp/soc_config_gen.yaml
# NOTE: Auto-generated file. Do not edit manually.

-f /workspace/nc-project-20260529-210526/.mspm33c321a_derivative_mcu_socgen_tmp/rtl/mspm33c321a_derivative_compute_ss.f
-f /workspace/nc-project-20260529-210526/.mspm33c321a_derivative_mcu_socgen_tmp/tb/mspm33c321a_derivative_compute_ss.f
