// Copyright (c) 2026 NC Factory
// Author: NC MCU Factory Requirements Agent
// License: Apache-2.0
// Generated by: nc_socgen/scripts/gen_soc.py
// Generator version: 1.1.0
// Generation UTC: 2026-05-29T04:57:53.077343+00:00
// Source config: /tmp/soc_config_gen.yaml
// NOTE: Auto-generated file. Do not edit manually.

`timescale 1ns/1ps
`default_nettype none

// Auto-generated AHB-Lite BFM smoke TB template
// Uses hierarchical-force host access on DUT fabric masters for directed checks.

module tb_mspm33c321a_derivative_compute_ss_smoke_bfm;

    reg clk;
    reg reset_n;
    reg  swclk;
    reg  swdi;
    wire swdo;
    wire swdo_en;
    reg  [15:0] gpioa_in;
    wire [15:0] gpioa_out;
    wire [15:0] gpioa_oe;
    reg  [15:0] gpiob_in;
    wire [15:0] gpiob_out;
    wire [15:0] gpiob_oe;
    reg  [15:0] gpioc_in;
    wire [15:0] gpioc_out;
    wire [15:0] gpioc_oe;
    wire qspi_sck;
    wire qspi_ce_n;
    wire [3:0] qspi_din;
    wire [3:0] qspi_dout;
    wire [3:0] qspi_douten;
    tri  [3:0] qspi_io;
    wire [11:0] clk_rst_pwr_paddr;
    wire        clk_rst_pwr_psel;
    wire        clk_rst_pwr_penable;
    wire        clk_rst_pwr_pwrite;
    wire [31:0] clk_rst_pwr_pwdata;
    reg  [31:0] clk_rst_pwr_prdata;
    reg         clk_rst_pwr_pready;
    reg         clk_rst_pwr_pslverr;
    wire [11:0] io_cfg_ss_paddr;
    wire        io_cfg_ss_psel;
    wire        io_cfg_ss_penable;
    wire        io_cfg_ss_pwrite;
    wire [31:0] io_cfg_ss_pwdata;
    reg  [31:0] io_cfg_ss_prdata;
    reg         io_cfg_ss_pready;
    reg         io_cfg_ss_pslverr;
    wire halted;

    reg [31:0] rd_data;
    integer smoke_reads;
    integer smoke_writes;
    integer smoke_errors;

    reg [31:0] host_haddr;
    reg [1:0]  host_htrans;
    reg        host_hwrite;
    reg [2:0]  host_hsize;
    reg [2:0]  host_hburst;
    reg [3:0]  host_hprot;
    reg [31:0] host_hwdata;
    reg        contention_stats_en;
    reg        m0_track_active;
    reg        m1_track_active;
    reg        m2_track_active;
    integer m0_wait_cur;
    integer m1_wait_cur;
    integer m2_wait_cur;
    integer m0_wait_sum;
    integer m1_wait_sum;
    integer m2_wait_sum;
    integer m0_wait_max;
    integer m1_wait_max;
    integer m2_wait_max;
    integer m0_req_cnt;
    integer m1_req_cnt;
    integer m2_req_cnt;
    integer m0_done_cnt;
    integer m1_done_cnt;
    integer m2_done_cnt;
    integer host_done_cnt;
    integer host_wait_sum;
    integer host_wait_max;
    integer host_err_cnt;
    reg [31:0] contention_tmp;
    reg [31:0] contention_tmp2;
    integer tb_cycle_count;
    integer flash_init_idx;

    localparam [1:0] AHB_TRANS_IDLE   = 2'b00;
    localparam [1:0] AHB_TRANS_NONSEQ = 2'b10;
    localparam [2:0] AHB_SIZE_WORD    = 3'b010;
    localparam [2:0] AHB_BURST_SINGLE = 3'b000;
    localparam [3:0] AHB_PROT_DATA    = 4'b0011;
    localparam integer MAX_AHB_WAIT   = 4096;
    localparam integer CONT_MAX_AHB_WAIT = 16;
    localparam integer CONT_HOST_MAX_AHB_WAIT = 256;
    localparam integer TB_MAX_CYCLES = 20000;
    localparam [31:0] CONT_SRAM_BASE = 32'h20000000;
    localparam [31:0] CONT_SRAM_SIZE = 32'h00020000;
    localparam integer CONT_HAS_DMAC = 1;
    localparam [31:0] CONT_DMAC_BASE = 32'h40014000;
    localparam integer CONT_DMAC_PRIORITY_HIGH = 0;
    localparam integer CONT_HAS_HOST = 0;
    localparam integer CONT_HOST_MASTER = -1;
    localparam integer CONT_CPU_USES_M0 = 1;
    localparam integer CONT_CPU_USES_M1 = 1;
    localparam integer CONT_EXPECT_CPU_M0 = CONT_CPU_USES_M0 && !(CONT_HAS_HOST && (CONT_HOST_MASTER == 0));
    localparam integer CONT_EXPECT_CPU_M1 = CONT_CPU_USES_M1 && !(CONT_HAS_HOST && (CONT_HOST_MASTER == 1));
    localparam integer CONT_CPU_STRICT = 1;
`ifdef TEST_SEQ_CONTENTION
    localparam RUN_SMOKE = 0;
`else
    localparam RUN_SMOKE = 1;
`endif

    always #5 clk = ~clk;

    mspm33c321a_derivative_compute_ss dut (
        .clk(clk),
        .reset_n(reset_n),
        .swclk(swclk),
        .swdi(swdi),
        .swdo(swdo),
        .swdo_en(swdo_en),
        .gpioa_in(gpioa_in),
        .gpioa_out(gpioa_out),
        .gpioa_oe(gpioa_oe),
        .gpiob_in(gpiob_in),
        .gpiob_out(gpiob_out),
        .gpiob_oe(gpiob_oe),
        .gpioc_in(gpioc_in),
        .gpioc_out(gpioc_out),
        .gpioc_oe(gpioc_oe),
        .qspi_sck(qspi_sck),
        .qspi_ce_n(qspi_ce_n),
        .qspi_din(qspi_din),
        .qspi_dout(qspi_dout),
        .qspi_douten(qspi_douten),
        .clk_rst_pwr_paddr(clk_rst_pwr_paddr),
        .clk_rst_pwr_psel(clk_rst_pwr_psel),
        .clk_rst_pwr_penable(clk_rst_pwr_penable),
        .clk_rst_pwr_pwrite(clk_rst_pwr_pwrite),
        .clk_rst_pwr_pwdata(clk_rst_pwr_pwdata),
        .clk_rst_pwr_prdata(clk_rst_pwr_prdata),
        .clk_rst_pwr_pready(clk_rst_pwr_pready),
        .clk_rst_pwr_pslverr(clk_rst_pwr_pslverr),
        .io_cfg_ss_paddr(io_cfg_ss_paddr),
        .io_cfg_ss_psel(io_cfg_ss_psel),
        .io_cfg_ss_penable(io_cfg_ss_penable),
        .io_cfg_ss_pwrite(io_cfg_ss_pwrite),
        .io_cfg_ss_pwdata(io_cfg_ss_pwdata),
        .io_cfg_ss_prdata(io_cfg_ss_prdata),
        .io_cfg_ss_pready(io_cfg_ss_pready),
        .io_cfg_ss_pslverr(io_cfg_ss_pslverr),
        .halted(halted)
    );

    assign qspi_din = qspi_io;
    assign qspi_io[0] = qspi_douten[0] ? qspi_dout[0] : 1'bz;
    assign qspi_io[1] = qspi_douten[1] ? qspi_dout[1] : 1'bz;
    assign qspi_io[2] = qspi_douten[2] ? qspi_dout[2] : 1'bz;
    assign qspi_io[3] = qspi_douten[3] ? qspi_dout[3] : 1'bz;
    pullup(qspi_io[0]);
    pullup(qspi_io[1]);
    pullup(qspi_io[2]);
    pullup(qspi_io[3]);
    sst26wf080b flash_i (
        .SCK (qspi_sck),
        .SIO (qspi_io),
        .CEb (qspi_ce_n)
    );
    initial begin
        for (flash_init_idx = 0; flash_init_idx < 1024*1024; flash_init_idx = flash_init_idx + 1) begin
            flash_i.I0.memory[flash_init_idx] = 8'h13;
        end
        // Deterministic RV32IM loop used by contention mode.
        // Program body:
        //   lui  x1, 0x20000
        //   addi x2, x0, 0
        // loop:
        //   lw   x3, 0(x1)
        //   addi x2, x2, 1
        //   sw   x2, 4(x1)
        //   jal  x0, loop
        flash_i.I0.memory[0]  = 8'hb7;
        flash_i.I0.memory[1]  = 8'h00;
        flash_i.I0.memory[2]  = 8'h00;
        flash_i.I0.memory[3]  = 8'h20;
        flash_i.I0.memory[4]  = 8'h13;
        flash_i.I0.memory[5]  = 8'h01;
        flash_i.I0.memory[6]  = 8'h00;
        flash_i.I0.memory[7]  = 8'h00;
        flash_i.I0.memory[8]  = 8'h83;
        flash_i.I0.memory[9]  = 8'ha1;
        flash_i.I0.memory[10] = 8'h00;
        flash_i.I0.memory[11] = 8'h00;
        flash_i.I0.memory[12] = 8'h13;
        flash_i.I0.memory[13] = 8'h01;
        flash_i.I0.memory[14] = 8'h11;
        flash_i.I0.memory[15] = 8'h00;
        flash_i.I0.memory[16] = 8'h23;
        flash_i.I0.memory[17] = 8'ha2;
        flash_i.I0.memory[18] = 8'h20;
        flash_i.I0.memory[19] = 8'h00;
        flash_i.I0.memory[20] = 8'h6f;
        flash_i.I0.memory[21] = 8'hf0;
        flash_i.I0.memory[22] = 8'h5f;
        flash_i.I0.memory[23] = 8'hff;
    end

    task automatic ahb_host_idle;
        begin
            host_haddr  = 32'h0000_0000;
            host_htrans = AHB_TRANS_IDLE;
            host_hwrite = 1'b0;
            host_hsize  = AHB_SIZE_WORD;
            host_hburst = AHB_BURST_SINGLE;
            host_hprot  = AHB_PROT_DATA;
            host_hwdata = 32'h0000_0000;
        end
    endtask

    task automatic ahb_wait_ready;
        output timeout;
        integer wait_cycles;
        begin: wait_loop
            timeout = 1'b0;
            wait_cycles = 0;
            while (dut.m0_hready !== 1'b1) begin
                @(posedge clk);
                wait_cycles = wait_cycles + 1;
                if (wait_cycles > MAX_AHB_WAIT) begin
                    timeout = 1'b1;
                    disable wait_loop;
                end
            end
        end
    endtask

    task automatic smoke_read32;
        input  [31:0] addr;
        output [31:0] data;
        reg timeout;
        begin
            data = 32'h0000_0000;
            if (addr[1:0] != 2'b00) begin
                smoke_errors = smoke_errors + 1;
                $display("SMOKE_READ unaligned addr=0x%08x", addr);
            end else begin
                @(posedge clk);
                host_haddr  = addr;
                host_htrans = AHB_TRANS_NONSEQ;
                host_hwrite = 1'b0;
                host_hsize  = AHB_SIZE_WORD;
                host_hburst = AHB_BURST_SINGLE;
                host_hprot  = AHB_PROT_DATA;
                host_hwdata = 32'h0000_0000;
                @(posedge clk);
                ahb_wait_ready(timeout);
                if (timeout) begin
                    smoke_errors = smoke_errors + 1;
                    $display("SMOKE_READ timeout addr=0x%08x", addr);
                end else begin
                    // Some AHB->APB bridges present read data one cycle
                    // after HREADY returns high; sample on the next edge.
                    @(posedge clk);
                    data = dut.m0_hrdata;
                    if (dut.m0_hresp !== 1'b0) begin
                        smoke_errors = smoke_errors + 1;
                        $display("SMOKE_READ HRESP error addr=0x%08x", addr);
                    end
                end
                ahb_host_idle();
                smoke_reads = smoke_reads + 1;
            end
        end
    endtask

    task automatic smoke_write32;
        input [31:0] addr;
        input [31:0] data;
        reg timeout;
        begin
            if (addr[1:0] != 2'b00) begin
                smoke_errors = smoke_errors + 1;
                $display("SMOKE_WRITE unaligned addr=0x%08x", addr);
            end else begin
                @(posedge clk);
                host_haddr  = addr;
                host_htrans = AHB_TRANS_NONSEQ;
                host_hwrite = 1'b1;
                host_hsize  = AHB_SIZE_WORD;
                host_hburst = AHB_BURST_SINGLE;
                host_hprot  = AHB_PROT_DATA;
                host_hwdata = data;
                @(posedge clk);
                ahb_wait_ready(timeout);
                if (timeout) begin
                    smoke_errors = smoke_errors + 1;
                    $display("SMOKE_WRITE timeout addr=0x%08x data=0x%08x", addr, data);
                end else begin
                    if (dut.m0_hresp !== 1'b0) begin
                        smoke_errors = smoke_errors + 1;
                        $display("SMOKE_WRITE HRESP error addr=0x%08x data=0x%08x", addr, data);
                    end
                end
                ahb_host_idle();
                smoke_writes = smoke_writes + 1;
            end
        end
    endtask

    task automatic smoke_expect_eq;
        input [31:0] addr;
        input [31:0] got;
        input [31:0] exp;
        begin
            if (got !== exp) begin
                smoke_errors = smoke_errors + 1;
                $display("SMOKE_MISMATCH: addr=0x%08x got=0x%08x exp=0x%08x", addr, got, exp);
            end
        end
    endtask

    task automatic contention_reset_stats;
        begin
            contention_stats_en = 1'b0;
            m0_track_active = 1'b0;
            m1_track_active = 1'b0;
            m2_track_active = 1'b0;
            m0_wait_cur = 0;
            m1_wait_cur = 0;
            m2_wait_cur = 0;
            m0_wait_sum = 0;
            m1_wait_sum = 0;
            m2_wait_sum = 0;
            m0_wait_max = 0;
            m1_wait_max = 0;
            m2_wait_max = 0;
            m0_req_cnt = 0;
            m1_req_cnt = 0;
            m2_req_cnt = 0;
            m0_done_cnt = 0;
            m1_done_cnt = 0;
            m2_done_cnt = 0;
            host_done_cnt = 0;
            host_wait_sum = 0;
            host_wait_max = 0;
            host_err_cnt = 0;
            contention_tmp = 32'h0;
            contention_tmp2 = 32'h0;
        end
    endtask

    task automatic contention_bind_host_master;
        begin
            if (CONT_HAS_HOST && (CONT_HOST_MASTER == 0)) begin
                force dut.m0_haddr_req  = host_haddr;
                force dut.m0_htrans_req = host_htrans;
                force dut.m0_hwrite_req = host_hwrite;
                force dut.m0_hsize_req  = host_hsize;
                force dut.m0_hburst_req = host_hburst;
                force dut.m0_hprot_req  = host_hprot;
                force dut.m0_hwdata_req = host_hwdata;
            end else if (CONT_HAS_HOST && (CONT_HOST_MASTER == 1)) begin
                force dut.m1_haddr_req  = host_haddr;
                force dut.m1_htrans_req = host_htrans;
                force dut.m1_hwrite_req = host_hwrite;
                force dut.m1_hsize_req  = host_hsize;
                force dut.m1_hburst_req = host_hburst;
                force dut.m1_hprot_req  = host_hprot;
                force dut.m1_hwdata_req = host_hwdata;
            end else if (CONT_HAS_HOST && (CONT_HOST_MASTER == 2)) begin
                force dut.m2_haddr_req  = host_haddr;
                force dut.m2_htrans_req = host_htrans;
                force dut.m2_hwrite_req = host_hwrite;
                force dut.m2_hsize_req  = host_hsize;
                force dut.m2_hburst_req = host_hburst;
                force dut.m2_hprot_req  = host_hprot;
                force dut.m2_hwdata_req = host_hwdata;
            end
        end
    endtask

    task automatic contention_release_host_master;
        begin
            if (CONT_HAS_HOST && (CONT_HOST_MASTER == 0)) begin
                release dut.m0_haddr_req;
                release dut.m0_htrans_req;
                release dut.m0_hwrite_req;
                release dut.m0_hsize_req;
                release dut.m0_hburst_req;
                release dut.m0_hprot_req;
                release dut.m0_hwdata_req;
            end else if (CONT_HAS_HOST && (CONT_HOST_MASTER == 1)) begin
                release dut.m1_haddr_req;
                release dut.m1_htrans_req;
                release dut.m1_hwrite_req;
                release dut.m1_hsize_req;
                release dut.m1_hburst_req;
                release dut.m1_hprot_req;
                release dut.m1_hwdata_req;
            end else if (CONT_HAS_HOST && (CONT_HOST_MASTER == 2)) begin
                release dut.m2_haddr_req;
                release dut.m2_htrans_req;
                release dut.m2_hwrite_req;
                release dut.m2_hsize_req;
                release dut.m2_hburst_req;
                release dut.m2_hprot_req;
                release dut.m2_hwdata_req;
            end
        end
    endtask

    task automatic contention_host_wait;
        output timeout;
        output [31:0] rdata;
        output hresp;
        integer wait_cycles;
        reg ready_now;
        reg done;
        begin
            timeout = 1'b0;
            rdata = 32'h0;
            hresp = 1'b0;
            done = 1'b0;
            wait_cycles = 0;
            while (!done) begin
                ready_now = 1'b0;
                if (CONT_HOST_MASTER == 0) ready_now = (dut.m0_hready === 1'b1);
                if (CONT_HOST_MASTER == 1) ready_now = (dut.m1_hready === 1'b1);
                if (CONT_HOST_MASTER == 2) ready_now = (dut.m2_hready === 1'b1);
                if (ready_now) begin
                    @(posedge clk);
                    if (CONT_HOST_MASTER == 0) begin
                        rdata = dut.m0_hrdata;
                        hresp = dut.m0_hresp;
                    end
                    if (CONT_HOST_MASTER == 1) begin
                        rdata = dut.m1_hrdata;
                        hresp = dut.m1_hresp;
                    end
                    if (CONT_HOST_MASTER == 2) begin
                        rdata = dut.m2_hrdata;
                        hresp = dut.m2_hresp;
                    end
                    done = 1'b1;
                end else begin
                    @(posedge clk);
                    wait_cycles = wait_cycles + 1;
                    if (wait_cycles > CONT_HOST_MAX_AHB_WAIT) begin
                        timeout = 1'b1;
                        done = 1'b1;
                    end
                end
            end
            if (!timeout) begin
                host_done_cnt = host_done_cnt + 1;
                host_wait_sum = host_wait_sum + wait_cycles;
                if (wait_cycles > host_wait_max) host_wait_max = wait_cycles;
            end else begin
                host_err_cnt = host_err_cnt + 1;
                smoke_errors = smoke_errors + 1;
                $display("CONTENTION host timeout");
            end
        end
    endtask

    task automatic contention_host_read32;
        input [31:0] addr;
        output [31:0] data;
        reg timeout;
        reg hresp;
        begin
            data = 32'h0;
            @(posedge clk);
            host_haddr  = addr;
            host_htrans = AHB_TRANS_NONSEQ;
            host_hwrite = 1'b0;
            host_hsize  = AHB_SIZE_WORD;
            host_hburst = AHB_BURST_SINGLE;
            host_hprot  = AHB_PROT_DATA;
            host_hwdata = 32'h0;
            @(posedge clk);
            contention_host_wait(timeout, data, hresp);
            if (!timeout && (hresp !== 1'b0)) begin
                host_err_cnt = host_err_cnt + 1;
                smoke_errors = smoke_errors + 1;
                $display("CONTENTION read HRESP error addr=0x%08x", addr);
            end
            ahb_host_idle();
        end
    endtask

    task automatic contention_host_write32;
        input [31:0] addr;
        input [31:0] data;
        reg timeout;
        reg [31:0] rdata_unused;
        reg hresp;
        begin
            @(posedge clk);
            host_haddr  = addr;
            host_htrans = AHB_TRANS_NONSEQ;
            host_hwrite = 1'b1;
            host_hsize  = AHB_SIZE_WORD;
            host_hburst = AHB_BURST_SINGLE;
            host_hprot  = AHB_PROT_DATA;
            host_hwdata = data;
            @(posedge clk);
            contention_host_wait(timeout, rdata_unused, hresp);
            if (!timeout && (hresp !== 1'b0)) begin
                host_err_cnt = host_err_cnt + 1;
                smoke_errors = smoke_errors + 1;
                $display("CONTENTION write HRESP error addr=0x%08x", addr);
            end
            ahb_host_idle();
        end
    endtask

    task automatic contention_prime_sram;
        input [31:0] src;
        input [31:0] dst;
        input integer words;
        integer i;
        begin
            for (i = 0; i < words; i = i + 1) begin
                contention_host_write32(src + (i << 2), (32'hCAFE0000 + i) ^ src);
                contention_host_write32(dst + (i << 2), 32'h00000000);
            end
        end
    endtask

    task automatic contention_configure_dma_mem2mem;
        input [31:0] src;
        input [31:0] dst;
        input integer words;
        reg [31:0] ch0_cr_cfg;
        begin
            // CH0_CR: EN|PINC|MINC|PSIZE=word|MSIZE=word|PL=very_high|MEM2MEM
            ch0_cr_cfg = 32'h00007EC1;
            contention_host_write32(CONT_DMAC_BASE + 32'h000, 32'h00000001); // CR.EN
            contention_host_write32(CONT_DMAC_BASE + 32'h208, src);
            contention_host_write32(CONT_DMAC_BASE + 32'h20C, dst);
            contention_host_write32(CONT_DMAC_BASE + 32'h210, words[15:0]);
            contention_host_write32(CONT_DMAC_BASE + 32'h200, ch0_cr_cfg);
        end
    endtask

    task automatic contention_start_dma_channel0;
        begin
            contention_host_write32(CONT_DMAC_BASE + 32'h100, 32'h00000001); // GCTL.CHEN0
        end
    endtask

    task automatic contention_run_host_poll;
        input integer polls;
        input [31:0] addr;
        integer i;
        begin
            for (i = 0; i < polls; i = i + 1) begin
                contention_host_read32(addr, contention_tmp);
            end
        end
    endtask

    task automatic contention_run_host_workload;
        input integer ops;
        input [31:0] base_addr;
        integer i;
        reg [31:0] op_addr;
        reg [31:0] op_data;
        begin
            for (i = 0; i < ops; i = i + 1) begin
                op_addr = base_addr + ((i & 16'h1F) << 2);
                if (i[0]) begin
                    op_data = (32'h5A5A0000 ^ i) + base_addr;
                    contention_host_write32(op_addr, op_data);
                end else begin
                    contention_host_read32(op_addr, contention_tmp);
                end
            end
        end
    endtask

    task automatic contention_check_dma_copy;
        input [31:0] src;
        input [31:0] dst;
        input integer samples;
        integer i;
        begin
            for (i = 0; i < samples; i = i + 1) begin
                contention_host_read32(src + (i << 2), contention_tmp);
                contention_host_read32(dst + (i << 2), contention_tmp2);
                if (contention_tmp2 !== contention_tmp) begin
                    smoke_errors = smoke_errors + 1;
                    $display("CONTENTION DMA copy mismatch idx=%0d src=0x%08x dst=0x%08x", i, contention_tmp, contention_tmp2);
                end
            end
        end
    endtask

    task automatic contention_report_stats;
        integer m0_avg;
        integer m1_avg;
        integer m2_avg;
        integer host_avg;
        integer cpu_ref_avg;
        reg cpu_ref_valid;
        begin
            m0_avg = (m0_done_cnt > 0) ? (m0_wait_sum / m0_done_cnt) : 0;
            m1_avg = (m1_done_cnt > 0) ? (m1_wait_sum / m1_done_cnt) : 0;
            m2_avg = (m2_done_cnt > 0) ? (m2_wait_sum / m2_done_cnt) : 0;
            host_avg = (host_done_cnt > 0) ? (host_wait_sum / host_done_cnt) : 0;
            cpu_ref_avg = 0;
            cpu_ref_valid = 1'b0;
            if (CONT_EXPECT_CPU_M0 && (m0_done_cnt > 8)) begin
                cpu_ref_avg = m0_avg;
                cpu_ref_valid = 1'b1;
            end else if (CONT_EXPECT_CPU_M1 && (m1_done_cnt > 8)) begin
                cpu_ref_avg = m1_avg;
                cpu_ref_valid = 1'b1;
            end
            $display("CONTENTION_SUMMARY m0_req=%0d m0_cnt=%0d m0_avg_wait=%0d m0_max=%0d m1_req=%0d m1_cnt=%0d m1_avg_wait=%0d m1_max=%0d m2_req=%0d m2_cnt=%0d m2_avg_wait=%0d m2_max=%0d host_cnt=%0d host_avg_wait=%0d host_max=%0d host_err=%0d",
                m0_req_cnt,
                m0_done_cnt, m0_avg, m0_wait_max,
                m1_req_cnt,
                m1_done_cnt, m1_avg, m1_wait_max,
                m2_req_cnt,
                m2_done_cnt, m2_avg, m2_wait_max,
                host_done_cnt, host_avg, host_wait_max, host_err_cnt);
            if (CONT_EXPECT_CPU_M0 && (m0_req_cnt == 0)) begin
                if (CONT_CPU_STRICT) begin
                    smoke_errors = smoke_errors + 1;
                    $display("CONTENTION_FAIL: CPU master m0 had zero observed requests");
                end else begin
                    $display("CONTENTION_WARN: CPU master m0 had zero observed requests");
                end
            end
            if (CONT_EXPECT_CPU_M1 && (m1_req_cnt == 0)) begin
                if (CONT_CPU_STRICT) begin
                    smoke_errors = smoke_errors + 1;
                    $display("CONTENTION_FAIL: CPU master m1 had zero observed requests");
                end else begin
                    $display("CONTENTION_WARN: CPU master m1 had zero observed requests");
                end
            end
            if (CONT_HAS_DMAC && (m2_done_cnt == 0)) begin
                smoke_errors = smoke_errors + 1;
                $display("CONTENTION_FAIL: DMA master m2 had zero completed transfers");
            end
            if (CONT_HAS_HOST && (host_done_cnt == 0)) begin
                smoke_errors = smoke_errors + 1;
                $display("CONTENTION_FAIL: host BFM had zero completed transfers");
            end
            if ((m0_wait_max > (MAX_AHB_WAIT/2)) || (m1_wait_max > (MAX_AHB_WAIT/2)) || (m2_wait_max > (MAX_AHB_WAIT/2))) begin
                smoke_errors = smoke_errors + 1;
                $display("CONTENTION_FAIL: starvation-like latency observed");
            end
            if (CONT_HAS_DMAC && cpu_ref_valid && (m2_done_cnt > 8)) begin
                if (CONT_DMAC_PRIORITY_HIGH && (m2_avg > (cpu_ref_avg + 8))) begin
                    smoke_errors = smoke_errors + 1;
                    $display("CONTENTION_FAIL: expected high-priority DMA latency <= CPU latency");
                end
                if ((!CONT_DMAC_PRIORITY_HIGH) && ((m2_avg + 8) < cpu_ref_avg)) begin
                    smoke_errors = smoke_errors + 1;
                    $display("CONTENTION_FAIL: expected low-priority DMA latency >= CPU latency");
                end
            end
        end
    endtask

    always @(posedge clk or negedge reset_n) begin
        if (!reset_n) begin
            m0_track_active <= 1'b0;
            m1_track_active <= 1'b0;
            m2_track_active <= 1'b0;
            m0_wait_cur <= 0;
            m1_wait_cur <= 0;
            m2_wait_cur <= 0;
        end else if (!contention_stats_en) begin
            m0_track_active <= 1'b0;
            m1_track_active <= 1'b0;
            m2_track_active <= 1'b0;
            m0_wait_cur <= 0;
            m1_wait_cur <= 0;
            m2_wait_cur <= 0;
        end else begin
            if (dut.m0_htrans_req[1]) m0_req_cnt <= m0_req_cnt + 1;
            if (dut.m1_htrans_req[1]) m1_req_cnt <= m1_req_cnt + 1;
            if (dut.m2_htrans_req[1]) m2_req_cnt <= m2_req_cnt + 1;
            if (!m0_track_active) begin
                if (dut.m0_htrans_req[1]) begin
                    m0_track_active <= 1'b1;
                    m0_wait_cur <= 0;
                end
            end else begin
                if (dut.m0_hready) begin
                    m0_done_cnt <= m0_done_cnt + 1;
                    m0_wait_sum <= m0_wait_sum + m0_wait_cur;
                    if (m0_wait_cur > m0_wait_max) m0_wait_max <= m0_wait_cur;
                    m0_track_active <= 1'b0;
                end else begin
                    m0_wait_cur <= m0_wait_cur + 1;
                end
            end
            if (!m1_track_active) begin
                if (dut.m1_htrans_req[1]) begin
                    m1_track_active <= 1'b1;
                    m1_wait_cur <= 0;
                end
            end else begin
                if (dut.m1_hready) begin
                    m1_done_cnt <= m1_done_cnt + 1;
                    m1_wait_sum <= m1_wait_sum + m1_wait_cur;
                    if (m1_wait_cur > m1_wait_max) m1_wait_max <= m1_wait_cur;
                    m1_track_active <= 1'b0;
                end else begin
                    m1_wait_cur <= m1_wait_cur + 1;
                end
            end
            if (!m2_track_active) begin
                if (dut.m2_htrans_req[1]) begin
                    m2_track_active <= 1'b1;
                    m2_wait_cur <= 0;
                end
            end else begin
                if (dut.m2_hready) begin
                    m2_done_cnt <= m2_done_cnt + 1;
                    m2_wait_sum <= m2_wait_sum + m2_wait_cur;
                    if (m2_wait_cur > m2_wait_max) m2_wait_max <= m2_wait_cur;
                    m2_track_active <= 1'b0;
                end else begin
                    m2_wait_cur <= m2_wait_cur + 1;
                end
            end
        end
    end

    task automatic run_smoke_sequence;
        begin
`ifdef TEST_SEQ_RAND_SYS
`include "mspm33c321a_derivative_compute_ss_rand_sys_seq.vh"
`elsif TEST_SEQ_IRQ
`include "mspm33c321a_derivative_compute_ss_irq_directed_seq.vh"
`elsif TEST_SEQ_DMA
`include "mspm33c321a_derivative_compute_ss_dma_directed_seq.vh"
`elsif TEST_SEQ_XIP
`include "mspm33c321a_derivative_compute_ss_xip_directed_seq.vh"
`elsif TEST_SEQ_PINMUX
`include "mspm33c321a_derivative_compute_ss_pinmux_directed_seq.vh"
`elsif TEST_SEQ_CONTENTION
`include "mspm33c321a_derivative_compute_ss_contention_directed_seq.vh"
`elsif TEST_SEQ_GPIO
`include "mspm33c321a_derivative_compute_ss_gpio_seq.vh"
`elsif TEST_SEQ_UART
`include "mspm33c321a_derivative_compute_ss_uart_seq.vh"
`elsif TEST_SEQ_SPI
`include "mspm33c321a_derivative_compute_ss_spi_seq.vh"
`elsif TEST_SEQ_I2C
`include "mspm33c321a_derivative_compute_ss_i2c_seq.vh"
`elsif TEST_SEQ_TIMER
`include "mspm33c321a_derivative_compute_ss_timer_seq.vh"
`elsif TEST_SEQ_PWM
`include "mspm33c321a_derivative_compute_ss_pwm_seq.vh"
`elsif TEST_SEQ_CRC
`include "mspm33c321a_derivative_compute_ss_crc_seq.vh"
`elsif TEST_SEQ_AES
`include "mspm33c321a_derivative_compute_ss_aes_seq.vh"
`elsif TEST_SEQ_WWDT
`include "mspm33c321a_derivative_compute_ss_wwdt_seq.vh"
`elsif TEST_SEQ_RTC
`include "mspm33c321a_derivative_compute_ss_rtc_seq.vh"
`elsif TEST_SEQ_SRAM
`include "mspm33c321a_derivative_compute_ss_sram_seq.vh"
`elsif TEST_SEQ_SYS_RESET
`include "mspm33c321a_derivative_compute_ss_sys_reset_seq.vh"
`elsif TEST_SEQ_SWD
`include "mspm33c321a_derivative_compute_ss_swd_seq.vh"
`else
`include "mspm33c321a_derivative_compute_ss_smoke_seq.vh"
`endif
        end
    endtask

    always @(posedge clk or negedge reset_n) begin
        if (!reset_n) begin
            tb_cycle_count <= 0;
        end else begin
            tb_cycle_count <= tb_cycle_count + 1;
`ifdef TB_VERBOSE_PROGRESS
            if ((tb_cycle_count % 1000) == 0)
                $display("TB_PROGRESS cycles=%0d", tb_cycle_count);
`endif
            if (tb_cycle_count > TB_MAX_CYCLES) begin
                $display("FAIL: testbench timeout after %0d cycles", tb_cycle_count);
                $finish;
            end
        end
    end

    initial begin
        clk = 1'b0;
        reset_n = 1'b0;
        swclk = 1'b0;
        swdi = 1'b1;
        gpioa_in = 16'h0;
        gpiob_in = 16'h0;
        gpioc_in = 16'h0;
        clk_rst_pwr_prdata = 32'h0000_0000;
        clk_rst_pwr_pready = 1'b1;
        clk_rst_pwr_pslverr = 1'b0;
        io_cfg_ss_prdata = 32'h0000_0000;
        io_cfg_ss_pready = 1'b1;
        io_cfg_ss_pslverr = 1'b0;
        rd_data = 32'h0;
        smoke_reads = 0;
        smoke_writes = 0;
        smoke_errors = 0;
        tb_cycle_count = 0;
        contention_reset_stats();
        ahb_host_idle();
        repeat (8) @(posedge clk);
        reset_n = 1'b1;

        if (RUN_SMOKE) begin
            // Acquire fabric master m0 for host-driven smoke transactions.
            force dut.reset = 1'b1;
            force dut.m0_haddr_req  = host_haddr;
            force dut.m0_htrans_req = host_htrans;
            force dut.m0_hwrite_req = host_hwrite;
            force dut.m0_hsize_req  = host_hsize;
            force dut.m0_hburst_req = host_hburst;
            force dut.m0_hprot_req  = host_hprot;
            force dut.m0_hwdata_req = host_hwdata;
            force dut.m1_haddr_req  = 32'h0000_0000;
            force dut.m1_htrans_req = AHB_TRANS_IDLE;
            force dut.m1_hwrite_req = 1'b0;
            force dut.m1_hsize_req  = AHB_SIZE_WORD;
            force dut.m1_hburst_req = AHB_BURST_SINGLE;
            force dut.m1_hprot_req  = AHB_PROT_DATA;
            force dut.m1_hwdata_req = 32'h0000_0000;
            force dut.m2_haddr_req  = 32'h0000_0000;
            force dut.m2_htrans_req = AHB_TRANS_IDLE;
            force dut.m2_hwrite_req = 1'b0;
            force dut.m2_hsize_req  = AHB_SIZE_WORD;
            force dut.m2_hburst_req = AHB_BURST_SINGLE;
            force dut.m2_hprot_req  = AHB_PROT_DATA;
            force dut.m2_hwdata_req = 32'h0000_0000;
            repeat (4) @(posedge clk);
            run_smoke_sequence();
            $display("SMOKE_SUMMARY: reads=%0d writes=%0d errors=%0d", smoke_reads, smoke_writes, smoke_errors);
            if (smoke_errors == 0)
                $display("PASS: smoke sequence completed without mismatches");
            else
                $display("FAIL: smoke sequence reported %0d errors", smoke_errors);
            release dut.m0_haddr_req;
            release dut.m0_htrans_req;
            release dut.m0_hwrite_req;
            release dut.m0_hsize_req;
            release dut.m0_hburst_req;
            release dut.m0_hprot_req;
            release dut.m0_hwdata_req;
            release dut.m1_haddr_req;
            release dut.m1_htrans_req;
            release dut.m1_hwrite_req;
            release dut.m1_hsize_req;
            release dut.m1_hburst_req;
            release dut.m1_hprot_req;
            release dut.m1_hwdata_req;
            release dut.m2_haddr_req;
            release dut.m2_htrans_req;
            release dut.m2_hwrite_req;
            release dut.m2_hsize_req;
            release dut.m2_hburst_req;
            release dut.m2_hprot_req;
            release dut.m2_hwdata_req;
            release dut.reset;
        end else begin
            // Contention mode: CPU + DMA (if present) + host traffic on spare master.
            run_smoke_sequence();
            if (smoke_errors == 0)
                $display("PASS: smoke sequence completed without mismatches");
            else
                $display("FAIL: smoke sequence reported %0d errors", smoke_errors);
        end

        #100;
        $finish;
    end

endmodule

`default_nettype wire
