// Copyright (c) 2026 NC Factory
// Author: NC MCU Factory Requirements Agent
// License: Apache-2.0
// Generated by: nc_socgen/scripts/gen_soc.py
// Generator version: 1.1.0
// Generation UTC: 2026-05-29T04:57:53.077343+00:00
// Source config: /tmp/soc_config_gen.yaml
// NOTE: Auto-generated file. Do not edit manually.

`timescale 1ns/1ps
`default_nettype none

// Boot image: XiP byte-hex image loaded into the flash model.
`ifndef PROG_HEX
`define PROG_HEX "../fw/build/mspm33c321a_derivative_compute_ss_smoke_xip.hex"
`endif

module tb_mspm33c321a_derivative_compute_ss_fw_boot;
    localparam [31:0] TEST_STATUS_ADDR = 32'h20000000;
    localparam [31:0] TEST_PASS = 32'h0000_0001;
`ifndef FW_BOOT_MAX_CYCLES
    localparam integer MAX_CYCLES = 100_000;
`else
    localparam integer MAX_CYCLES = `FW_BOOT_MAX_CYCLES;
`endif

    reg clk;
    reg reset_n;
    reg  swclk;
    reg  swdi;
    wire swdo;
    wire swdo_en;
    reg  [15:0] gpioa_in;
    wire [15:0] gpioa_out;
    wire [15:0] gpioa_oe;
    reg  [15:0] gpiob_in;
    wire [15:0] gpiob_out;
    wire [15:0] gpiob_oe;
    reg  [15:0] gpioc_in;
    wire [15:0] gpioc_out;
    wire [15:0] gpioc_oe;
    wire qspi_sck;
    wire qspi_ce_n;
    wire [3:0] qspi_din;
    wire [3:0] qspi_dout;
    wire [3:0] qspi_douten;
    tri  [3:0] qspi_io;
    wire [11:0] clk_rst_pwr_paddr;
    wire        clk_rst_pwr_psel;
    wire        clk_rst_pwr_penable;
    wire        clk_rst_pwr_pwrite;
    wire [31:0] clk_rst_pwr_pwdata;
    reg  [31:0] clk_rst_pwr_prdata;
    reg         clk_rst_pwr_pready;
    reg         clk_rst_pwr_pslverr;
    wire [11:0] io_cfg_ss_paddr;
    wire        io_cfg_ss_psel;
    wire        io_cfg_ss_penable;
    wire        io_cfg_ss_pwrite;
    wire [31:0] io_cfg_ss_pwdata;
    reg  [31:0] io_cfg_ss_prdata;
    reg         io_cfg_ss_pready;
    reg         io_cfg_ss_pslverr;
    wire halted;
    integer cycles;
    reg [31:0] status_reg;
    reg status_seen;
    reg m0_status_pending;
    reg m1_status_pending;
    reg m2_status_pending;
    integer flash_init_idx;

    always #5 clk = ~clk;

    mspm33c321a_derivative_compute_ss dut (
        .clk(clk),
        .reset_n(reset_n),
        .swclk(swclk),
        .swdi(swdi),
        .swdo(swdo),
        .swdo_en(swdo_en),
        .gpioa_in(gpioa_in),
        .gpioa_out(gpioa_out),
        .gpioa_oe(gpioa_oe),
        .gpiob_in(gpiob_in),
        .gpiob_out(gpiob_out),
        .gpiob_oe(gpiob_oe),
        .gpioc_in(gpioc_in),
        .gpioc_out(gpioc_out),
        .gpioc_oe(gpioc_oe),
        .qspi_sck(qspi_sck),
        .qspi_ce_n(qspi_ce_n),
        .qspi_din(qspi_din),
        .qspi_dout(qspi_dout),
        .qspi_douten(qspi_douten),
        .clk_rst_pwr_paddr(clk_rst_pwr_paddr),
        .clk_rst_pwr_psel(clk_rst_pwr_psel),
        .clk_rst_pwr_penable(clk_rst_pwr_penable),
        .clk_rst_pwr_pwrite(clk_rst_pwr_pwrite),
        .clk_rst_pwr_pwdata(clk_rst_pwr_pwdata),
        .clk_rst_pwr_prdata(clk_rst_pwr_prdata),
        .clk_rst_pwr_pready(clk_rst_pwr_pready),
        .clk_rst_pwr_pslverr(clk_rst_pwr_pslverr),
        .io_cfg_ss_paddr(io_cfg_ss_paddr),
        .io_cfg_ss_psel(io_cfg_ss_psel),
        .io_cfg_ss_penable(io_cfg_ss_penable),
        .io_cfg_ss_pwrite(io_cfg_ss_pwrite),
        .io_cfg_ss_pwdata(io_cfg_ss_pwdata),
        .io_cfg_ss_prdata(io_cfg_ss_prdata),
        .io_cfg_ss_pready(io_cfg_ss_pready),
        .io_cfg_ss_pslverr(io_cfg_ss_pslverr),
        .halted(halted)
    );

    assign qspi_din = qspi_io;
    assign qspi_io[0] = qspi_douten[0] ? qspi_dout[0] : 1'bz;
    assign qspi_io[1] = qspi_douten[1] ? qspi_dout[1] : 1'bz;
    assign qspi_io[2] = qspi_douten[2] ? qspi_dout[2] : 1'bz;
    assign qspi_io[3] = qspi_douten[3] ? qspi_dout[3] : 1'bz;
    pullup(qspi_io[0]);
    pullup(qspi_io[1]);
    pullup(qspi_io[2]);
    pullup(qspi_io[3]);
    sst26wf080b flash_i (
        .SCK (qspi_sck),
        .SIO (qspi_io),
        .CEb (qspi_ce_n)
    );

    initial begin
        for (flash_init_idx = 0; flash_init_idx < 1024*1024; flash_init_idx = flash_init_idx + 1) begin
            flash_i.I0.memory[flash_init_idx] = 8'hFF;
        end
        #1 $readmemh(`PROG_HEX, flash_i.I0.memory);
    end


    initial begin
        clk = 1'b0;
        reset_n = 1'b0;
        swclk = 1'b0;
        swdi = 1'b1;
        gpioa_in = 16'hFF;
        gpiob_in = 16'hFF;
        gpioc_in = 16'hFF;
        clk_rst_pwr_prdata = 32'h0000_0000;
        clk_rst_pwr_pready = 1'b1;
        clk_rst_pwr_pslverr = 1'b0;
        io_cfg_ss_prdata = 32'h0000_0000;
        io_cfg_ss_pready = 1'b1;
        io_cfg_ss_pslverr = 1'b0;
        status_reg = 32'h0;
        status_seen = 1'b0;
        m0_status_pending = 1'b0;
        m1_status_pending = 1'b0;
        m2_status_pending = 1'b0;
        cycles = 0;
        repeat (10) @(posedge clk);
        reset_n = 1'b1;
        $display("FW_BOOT: mode=XIP");

        while (cycles < MAX_CYCLES) begin
            @(posedge clk);
            cycles = cycles + 1;
            if (m0_status_pending && dut.m0_hready) begin
                status_reg        = dut.m0_hwdata_req;
                status_seen       = 1'b1;
                m0_status_pending = 1'b0;
            end
            if (m1_status_pending && dut.m1_hready) begin
                status_reg        = dut.m1_hwdata_req;
                status_seen       = 1'b1;
                m1_status_pending = 1'b0;
            end
            if (m2_status_pending && dut.m2_hready) begin
                status_reg        = dut.m2_hwdata_req;
                status_seen       = 1'b1;
                m2_status_pending = 1'b0;
            end
            if (dut.m0_htrans_req[1] && dut.m0_hwrite_req && (dut.m0_haddr_req == TEST_STATUS_ADDR)) begin
                if (dut.m0_hready) begin
                    m0_status_pending = 1'b1;
                end
            end
            if (dut.m1_htrans_req[1] && dut.m1_hwrite_req && (dut.m1_haddr_req == TEST_STATUS_ADDR)) begin
                if (dut.m1_hready) begin
                    m1_status_pending = 1'b1;
                end
            end
            if (dut.m2_htrans_req[1] && dut.m2_hwrite_req && (dut.m2_haddr_req == TEST_STATUS_ADDR)) begin
                if (dut.m2_hready) begin
                    m2_status_pending = 1'b1;
                end
            end
            if (status_seen && status_reg == TEST_PASS) begin
                $display("PASS: fw boot smoke");
                $finish;
            end
            if (status_seen && status_reg != 32'h0 && status_reg != TEST_PASS) begin
                $display("FAIL: status=0x%08x", status_reg);
                $finish;
            end
`ifdef TEST_STATUS_HIER
            status_reg = `TEST_STATUS_HIER;
            if (status_reg == TEST_PASS) begin
                $display("PASS: fw boot smoke");
                $finish;
            end
            if (status_reg != 32'h0 && status_reg != TEST_PASS) begin
                $display("FAIL: status=0x%08x", status_reg);
                $finish;
            end
`else
            if (halted) begin
                $display("INFO: halted asserted");
                $finish;
            end
`endif
        end

        $display("FAIL: timeout");
        $finish;
    end
endmodule

`default_nettype wire
