/*
 * Copyright (c) 2026 NC Factory
 * Author: NC MCU Factory Requirements Agent
 * License: Apache-2.0
 * Generated by: nc_socgen/scripts/gen_soc.py
 * Generator version: 1.1.0
 * Generation UTC: 2026-05-29T04:57:53.077343+00:00
 * Source config: /tmp/soc_config_gen.yaml
 * NOTE: Auto-generated file. Do not edit manually.
 */

#ifndef MSPM33C321A_DERIVATIVE_COMPUTE_SS_BOARD_H
#define MSPM33C321A_DERIVATIVE_COMPUTE_SS_BOARD_H

#include <stdint.h>
#include "soc_memmap.h"
#include "soc_irq.h"
#include "nc_drv_common.h"
#include "nc_aes_drv.h"
#include "nc_crc_drv.h"
#include "nc_dmac_drv.h"
#include "nc_gpio_drv.h"
#include "nc_i2c_drv.h"
#include "nc_pwm_drv.h"
#include "nc_rtc_drv.h"
#include "nc_spi_drv.h"
#include "nc_systick_drv.h"
#include "nc_tmr_drv.h"
#include "nc_uart_drv.h"
#include "nc_wwdt_drv.h"
#include "nc_xip_drv.h"

int soc_drivers_init(void);
uint32_t soc_gpio_count(void);
nc_gpio_dev_t *soc_get_gpio_dev(uint32_t index);

#endif /* MSPM33C321A_DERIVATIVE_COMPUTE_SS_BOARD_H */
