/*
 * Copyright (c) 2026 NC Factory
 * Author: NC MCU Factory Requirements Agent
 * License: Apache-2.0
 * Generated by: nc_socgen/scripts/gen_soc.py
 * Generator version: 1.1.0
 * Generation UTC: 2026-05-29T04:57:53.077343+00:00
 * Source config: /tmp/soc_config_gen.yaml
 * NOTE: Auto-generated file. Do not edit manually.
 */

#ifndef MSPM33C321A_DERIVATIVE_COMPUTE_SS_IRQ_H
#define MSPM33C321A_DERIVATIVE_COMPUTE_SS_IRQ_H

#include <stdint.h>

#define SOC_IRQ_COUNT      25u

#define SOC_IRQ_GPIO0      0u
#define SOC_IRQ_GPIO1      1u
#define SOC_IRQ_GPIO2      2u
#define SOC_IRQ_UART0      3u
#define SOC_IRQ_UART1      4u
#define SOC_IRQ_UART2      5u
#define SOC_IRQ_UART3      6u
#define SOC_IRQ_SPI0      7u
#define SOC_IRQ_SPI1      8u
#define SOC_IRQ_I2C0      9u
#define SOC_IRQ_I2C1      10u
#define SOC_IRQ_I2C2      11u
#define SOC_IRQ_TMR0      12u
#define SOC_IRQ_TMR1      13u
#define SOC_IRQ_TMR2      14u
#define SOC_IRQ_TMR3      15u
#define SOC_IRQ_TMR4      16u
#define SOC_IRQ_TMR5      17u
#define SOC_IRQ_PWM0      18u
#define SOC_IRQ_PWM1      19u
#define SOC_IRQ_DMAC0      20u
#define SOC_IRQ_CRC0      21u
#define SOC_IRQ_AES0      22u
#define SOC_IRQ_WWDT0      23u
#define SOC_IRQ_RTC0      24u

#endif /* MSPM33C321A_DERIVATIVE_COMPUTE_SS_IRQ_H */
