/*
 * Copyright (c) 2026 NC Factory
 * Author: NC MCU Factory Requirements Agent
 * License: Apache-2.0
 * Generated by: nc_socgen/scripts/gen_soc.py
 * Generator version: 1.1.0
 * Generation UTC: 2026-05-29T04:57:53.077343+00:00
 * Source config: /tmp/soc_config_gen.yaml
 * NOTE: Auto-generated file. Do not edit manually.
 */

#ifndef MSPM33C321A_DERIVATIVE_COMPUTE_SS_MEMMAP_H
#define MSPM33C321A_DERIVATIVE_COMPUTE_SS_MEMMAP_H

#include <stdint.h>

#define SOC_TOP_NAME "mspm33c321a_derivative_compute_ss"
#define SOC_TEST_STATUS_ADDR 0x20000000u
#define SOC_SRAM_BASE      0x20000000u
#define SOC_SRAM_SIZE      0x00020000u
#define SOC_XIP_BASE       0x00000000u
#define SOC_XIP_SIZE       0x00080000u

#define SOC_APB0_BASE      0x40000000u
#define SOC_APB0_SLOT_SIZE 0x00001000u
#define SOC_APB0_SLOTS     16u
#define SOC_APB1_BASE      0x40010000u
#define SOC_APB1_SLOT_SIZE 0x00001000u
#define SOC_APB1_SLOTS     16u

#define SOC_GPIO0_BASE      0x40000000u
#define SOC_GPIO0_SIZE      0x00001000u
#define SOC_GPIO1_BASE      0x40001000u
#define SOC_GPIO1_SIZE      0x00001000u
#define SOC_GPIO2_BASE      0x40002000u
#define SOC_GPIO2_SIZE      0x00001000u
#define SOC_UART0_BASE      0x40003000u
#define SOC_UART0_SIZE      0x00001000u
#define SOC_UART1_BASE      0x40004000u
#define SOC_UART1_SIZE      0x00001000u
#define SOC_UART2_BASE      0x40005000u
#define SOC_UART2_SIZE      0x00001000u
#define SOC_UART3_BASE      0x40006000u
#define SOC_UART3_SIZE      0x00001000u
#define SOC_SPI0_BASE      0x40007000u
#define SOC_SPI0_SIZE      0x00001000u
#define SOC_SPI1_BASE      0x40008000u
#define SOC_SPI1_SIZE      0x00001000u
#define SOC_I2C0_BASE      0x40009000u
#define SOC_I2C0_SIZE      0x00001000u
#define SOC_I2C1_BASE      0x4000A000u
#define SOC_I2C1_SIZE      0x00001000u
#define SOC_I2C2_BASE      0x4000B000u
#define SOC_I2C2_SIZE      0x00001000u
#define SOC_TMR0_BASE      0x4000C000u
#define SOC_TMR0_SIZE      0x00001000u
#define SOC_TMR1_BASE      0x4000D000u
#define SOC_TMR1_SIZE      0x00001000u
#define SOC_TMR2_BASE      0x4000E000u
#define SOC_TMR2_SIZE      0x00001000u
#define SOC_TMR3_BASE      0x4000F000u
#define SOC_TMR3_SIZE      0x00001000u
#define SOC_TMR4_BASE      0x40010000u
#define SOC_TMR4_SIZE      0x00001000u
#define SOC_TMR5_BASE      0x40011000u
#define SOC_TMR5_SIZE      0x00001000u
#define SOC_PWM0_BASE      0x40012000u
#define SOC_PWM0_SIZE      0x00001000u
#define SOC_PWM1_BASE      0x40013000u
#define SOC_PWM1_SIZE      0x00001000u
#define SOC_DMAC0_BASE      0x40014000u
#define SOC_DMAC0_SIZE      0x00001000u
#define SOC_CRC0_BASE      0x40015000u
#define SOC_CRC0_SIZE      0x00001000u
#define SOC_AES0_BASE      0x40016000u
#define SOC_AES0_SIZE      0x00001000u
#define SOC_WWDT0_BASE      0x40017000u
#define SOC_WWDT0_SIZE      0x00001000u
#define SOC_RTC0_BASE      0x40018000u
#define SOC_RTC0_SIZE      0x00001000u
#define SOC_SYSTICK0_BASE      0x4001E000u
#define SOC_SYSTICK0_SIZE      0x00001000u
#define SOC_CLK_RST_PWR_SS_BASE 0x4001D000u
#define SOC_CLK_RST_PWR_SS_SIZE 0x00001000u
#define SOC_IO_CFG_SS_BASE 0x4001C000u
#define SOC_IO_CFG_SS_SIZE 0x00001000u

#endif /* MSPM33C321A_DERIVATIVE_COMPUTE_SS_MEMMAP_H */
