#!/usr/bin/env python3
# Copyright (c) 2026 NC Factory
# Author: NC MCU Factory Requirements Agent
# License: Apache-2.0
# Generated by: nc_socgen/scripts/gen_soc.py
# Generator version: 1.1.0
# Generation UTC: 2026-05-29T04:57:53.077343+00:00
# Source config: /tmp/soc_config_gen.yaml
# NOTE: Auto-generated file. Do not edit manually.

"""Convert binary images to line-oriented hex files for simulation memories."""

from __future__ import annotations

import argparse
from pathlib import Path


def write_word_hex(data: bytes, out_path: Path, pad_words: int = 0) -> None:
    if len(data) % 4:
        data += b"\x00" * (4 - (len(data) % 4))

    words = []
    for idx in range(0, len(data), 4):
        b0, b1, b2, b3 = data[idx : idx + 4]
        val = b0 | (b1 << 8) | (b2 << 16) | (b3 << 24)
        words.append(f"{val:08x}")

    if pad_words > 0 and len(words) < pad_words:
        words.extend(["00000000"] * (pad_words - len(words)))

    out_path.write_text("\n".join(words) + "\n")


def write_byte_hex(data: bytes, out_path: Path) -> None:
    out_path.write_text("\n".join(f"{byte:02x}" for byte in data) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, help="Input binary file")
    parser.add_argument("--output", required=True, help="Output hex file")
    parser.add_argument(
        "--format",
        choices=("word", "byte"),
        default="word",
        help="Output format: 32-bit words per line (word) or bytes per line (byte)",
    )
    parser.add_argument(
        "--pad-words",
        type=int,
        default=0,
        help="Pad word output to at least this many words",
    )
    args = parser.parse_args()

    in_path = Path(args.input)
    out_path = Path(args.output)

    data = in_path.read_bytes()
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if args.format == "word":
        write_word_hex(data, out_path, pad_words=max(0, args.pad_words))
    else:
        write_byte_hex(data, out_path)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
