/*
 * Copyright (c) 2026 NC Factory
 * Author: NC MCU Factory Requirements Agent
 * License: Apache-2.0
 * Generated by: nc_socgen/scripts/gen_soc.py
 * Generator version: 1.1.0
 * Generation UTC: 2026-05-29T04:57:53.077343+00:00
 * Source config: /tmp/soc_config_gen.yaml
 * NOTE: Auto-generated file. Do not edit manually.
 */

#include <stddef.h>
#include "soc_pinmux.h"
#include "soc_board.h"

static const soc_pinmux_route_t g_soc_pinmux_routes[SOC_PINMUX_ROUTE_COUNT] = {
    {0u, 0u, 1u, SOC_PINMUX_DIR_OUT, "uart0.uart_tx"},
    {0u, 0u, 2u, SOC_PINMUX_DIR_IN, "uart0.uart_rx"},
    {0u, 0u, 3u, SOC_PINMUX_DIR_OUT, "uart1.uart_tx"},
    {0u, 0u, 4u, SOC_PINMUX_DIR_IN, "uart1.uart_rx"},
    {0u, 0u, 5u, SOC_PINMUX_DIR_OUT, "uart2.uart_tx"},
    {0u, 0u, 6u, SOC_PINMUX_DIR_IN, "uart2.uart_rx"},
    {0u, 0u, 7u, SOC_PINMUX_DIR_OUT, "uart3.uart_tx"},
    {0u, 0u, 8u, SOC_PINMUX_DIR_IN, "uart3.uart_rx"},
    {0u, 0u, 9u, SOC_PINMUX_DIR_OUT, "spi0.spi_sck"},
    {0u, 0u, 10u, SOC_PINMUX_DIR_OUT, "spi0.spi_mosi"},
    {0u, 0u, 11u, SOC_PINMUX_DIR_OUT, "spi0.spi_cs_n"},
    {0u, 0u, 12u, SOC_PINMUX_DIR_IN, "spi0.spi_miso"},
    {0u, 0u, 13u, SOC_PINMUX_DIR_OUT, "spi1.spi_sck"},
    {0u, 0u, 14u, SOC_PINMUX_DIR_OUT, "spi1.spi_mosi"},
    {0u, 0u, 15u, SOC_PINMUX_DIR_OUT, "spi1.spi_cs_n"},
    {0u, 1u, 1u, SOC_PINMUX_DIR_IN, "spi1.spi_miso"},
    {0u, 1u, 2u, SOC_PINMUX_DIR_OUT, "i2c0.i2c_scl_o"},
    {0u, 1u, 3u, SOC_PINMUX_DIR_OUT, "i2c0.i2c_sda_o"},
    {0u, 1u, 4u, SOC_PINMUX_DIR_IN, "i2c0.i2c_scl_i"},
    {0u, 1u, 5u, SOC_PINMUX_DIR_IN, "i2c0.i2c_sda_i"},
    {0u, 1u, 6u, SOC_PINMUX_DIR_OUT, "i2c1.i2c_scl_o"},
    {0u, 1u, 7u, SOC_PINMUX_DIR_OUT, "i2c1.i2c_sda_o"},
    {0u, 1u, 8u, SOC_PINMUX_DIR_IN, "i2c1.i2c_scl_i"},
    {0u, 1u, 9u, SOC_PINMUX_DIR_IN, "i2c1.i2c_sda_i"},
    {0u, 1u, 10u, SOC_PINMUX_DIR_OUT, "i2c2.i2c_scl_o"},
    {0u, 1u, 11u, SOC_PINMUX_DIR_OUT, "i2c2.i2c_sda_o"},
    {0u, 1u, 12u, SOC_PINMUX_DIR_IN, "i2c2.i2c_scl_i"},
    {0u, 1u, 13u, SOC_PINMUX_DIR_IN, "i2c2.i2c_sda_i"},
    {0u, 1u, 14u, SOC_PINMUX_DIR_IN, "tmr0.tmr_ti1"},
    {0u, 1u, 15u, SOC_PINMUX_DIR_IN, "tmr0.tmr_ti2"},
    {0u, 2u, 1u, SOC_PINMUX_DIR_IN, "tmr0.tmr_etr"},
    {0u, 2u, 2u, SOC_PINMUX_DIR_IN, "tmr0.tmr_bkin"},
    {0u, 2u, 3u, SOC_PINMUX_DIR_OUT, "tmr0.tmr_ch1"},
    {0u, 2u, 4u, SOC_PINMUX_DIR_OUT, "tmr0.tmr_ch1n"},
    {0u, 2u, 5u, SOC_PINMUX_DIR_OUT, "tmr0.tmr_ch2"},
    {0u, 2u, 6u, SOC_PINMUX_DIR_OUT, "tmr0.tmr_ch2n"},
    {0u, 2u, 7u, SOC_PINMUX_DIR_OUT, "tmr0.tmr_ch3"},
    {0u, 2u, 8u, SOC_PINMUX_DIR_OUT, "tmr0.tmr_ch3n"},
    {0u, 2u, 9u, SOC_PINMUX_DIR_OUT, "tmr0.tmr_ch4"},
    {0u, 2u, 10u, SOC_PINMUX_DIR_OUT, "tmr0.tmr_trgo"},
    {0u, 2u, 11u, SOC_PINMUX_DIR_IN, "tmr1.tmr_ti1"},
    {0u, 2u, 12u, SOC_PINMUX_DIR_IN, "tmr1.tmr_ti2"},
    {0u, 2u, 13u, SOC_PINMUX_DIR_IN, "tmr1.tmr_etr"},
    {0u, 2u, 14u, SOC_PINMUX_DIR_IN, "tmr1.tmr_bkin"},
    {0u, 2u, 15u, SOC_PINMUX_DIR_OUT, "tmr1.tmr_ch1"},
    {0u, 3u, 1u, SOC_PINMUX_DIR_OUT, "tmr1.tmr_ch1n"},
    {0u, 3u, 2u, SOC_PINMUX_DIR_OUT, "tmr1.tmr_ch2"},
    {0u, 3u, 3u, SOC_PINMUX_DIR_OUT, "tmr1.tmr_ch2n"},
    {0u, 3u, 4u, SOC_PINMUX_DIR_OUT, "tmr1.tmr_ch3"},
    {0u, 3u, 5u, SOC_PINMUX_DIR_OUT, "tmr1.tmr_ch3n"},
    {0u, 3u, 6u, SOC_PINMUX_DIR_OUT, "tmr1.tmr_ch4"},
    {0u, 3u, 7u, SOC_PINMUX_DIR_OUT, "tmr1.tmr_trgo"},
    {0u, 3u, 8u, SOC_PINMUX_DIR_IN, "tmr2.tmr_ti1"},
    {0u, 3u, 9u, SOC_PINMUX_DIR_IN, "tmr2.tmr_ti2"},
    {0u, 3u, 10u, SOC_PINMUX_DIR_IN, "tmr2.tmr_etr"},
    {0u, 3u, 11u, SOC_PINMUX_DIR_IN, "tmr2.tmr_bkin"},
    {0u, 3u, 12u, SOC_PINMUX_DIR_OUT, "tmr2.tmr_ch1"},
    {0u, 3u, 13u, SOC_PINMUX_DIR_OUT, "tmr2.tmr_ch1n"},
    {0u, 3u, 14u, SOC_PINMUX_DIR_OUT, "tmr2.tmr_ch2"},
    {0u, 3u, 15u, SOC_PINMUX_DIR_OUT, "tmr2.tmr_ch2n"},
    {0u, 4u, 1u, SOC_PINMUX_DIR_OUT, "tmr2.tmr_ch3"},
    {0u, 4u, 2u, SOC_PINMUX_DIR_OUT, "tmr2.tmr_ch3n"},
    {0u, 4u, 3u, SOC_PINMUX_DIR_OUT, "tmr2.tmr_ch4"},
    {0u, 4u, 4u, SOC_PINMUX_DIR_OUT, "tmr2.tmr_trgo"},
    {0u, 4u, 5u, SOC_PINMUX_DIR_IN, "tmr3.tmr_ti1"},
    {0u, 4u, 6u, SOC_PINMUX_DIR_IN, "tmr3.tmr_ti2"},
    {0u, 4u, 7u, SOC_PINMUX_DIR_IN, "tmr3.tmr_etr"},
    {0u, 4u, 8u, SOC_PINMUX_DIR_IN, "tmr3.tmr_bkin"},
    {0u, 4u, 9u, SOC_PINMUX_DIR_OUT, "tmr3.tmr_ch1"},
    {0u, 4u, 10u, SOC_PINMUX_DIR_OUT, "tmr3.tmr_ch1n"},
    {0u, 4u, 11u, SOC_PINMUX_DIR_OUT, "tmr3.tmr_ch2"},
    {0u, 4u, 12u, SOC_PINMUX_DIR_OUT, "tmr3.tmr_ch2n"},
    {0u, 4u, 13u, SOC_PINMUX_DIR_OUT, "tmr3.tmr_ch3"},
    {0u, 4u, 14u, SOC_PINMUX_DIR_OUT, "tmr3.tmr_ch3n"},
    {0u, 4u, 15u, SOC_PINMUX_DIR_OUT, "tmr3.tmr_ch4"},
    {0u, 5u, 1u, SOC_PINMUX_DIR_OUT, "tmr3.tmr_trgo"},
    {0u, 5u, 2u, SOC_PINMUX_DIR_IN, "tmr4.tmr_ti1"},
    {0u, 5u, 3u, SOC_PINMUX_DIR_IN, "tmr4.tmr_ti2"},
    {0u, 5u, 4u, SOC_PINMUX_DIR_IN, "tmr4.tmr_etr"},
    {0u, 5u, 5u, SOC_PINMUX_DIR_IN, "tmr4.tmr_bkin"},
    {0u, 5u, 6u, SOC_PINMUX_DIR_OUT, "tmr4.tmr_ch1"},
    {0u, 5u, 7u, SOC_PINMUX_DIR_OUT, "tmr4.tmr_ch1n"},
    {0u, 5u, 8u, SOC_PINMUX_DIR_OUT, "tmr4.tmr_ch2"},
    {0u, 5u, 9u, SOC_PINMUX_DIR_OUT, "tmr4.tmr_ch2n"},
    {0u, 5u, 10u, SOC_PINMUX_DIR_OUT, "tmr4.tmr_ch3"},
    {0u, 5u, 11u, SOC_PINMUX_DIR_OUT, "tmr4.tmr_ch3n"},
    {0u, 5u, 12u, SOC_PINMUX_DIR_OUT, "tmr4.tmr_ch4"},
    {0u, 5u, 13u, SOC_PINMUX_DIR_OUT, "tmr4.tmr_trgo"},
    {0u, 5u, 14u, SOC_PINMUX_DIR_IN, "tmr5.tmr_ti1"},
    {0u, 5u, 15u, SOC_PINMUX_DIR_IN, "tmr5.tmr_ti2"},
    {0u, 6u, 1u, SOC_PINMUX_DIR_IN, "tmr5.tmr_etr"},
    {0u, 6u, 2u, SOC_PINMUX_DIR_IN, "tmr5.tmr_bkin"},
    {0u, 6u, 3u, SOC_PINMUX_DIR_OUT, "tmr5.tmr_ch1"},
    {0u, 6u, 4u, SOC_PINMUX_DIR_OUT, "tmr5.tmr_ch1n"},
    {0u, 6u, 5u, SOC_PINMUX_DIR_OUT, "tmr5.tmr_ch2"},
    {0u, 6u, 6u, SOC_PINMUX_DIR_OUT, "tmr5.tmr_ch2n"},
    {0u, 6u, 7u, SOC_PINMUX_DIR_OUT, "tmr5.tmr_ch3"},
    {0u, 6u, 8u, SOC_PINMUX_DIR_OUT, "tmr5.tmr_ch3n"},
    {0u, 6u, 9u, SOC_PINMUX_DIR_OUT, "tmr5.tmr_ch4"},
    {0u, 6u, 10u, SOC_PINMUX_DIR_OUT, "tmr5.tmr_trgo"},
    {0u, 6u, 11u, SOC_PINMUX_DIR_IN, "pwm0.pwm_break_in"},
    {0u, 6u, 12u, SOC_PINMUX_DIR_IN, "pwm0.pwm_break_in2"},
    {0u, 6u, 13u, SOC_PINMUX_DIR_IN, "pwm0.pwm_ext_clk"},
    {0u, 6u, 14u, SOC_PINMUX_DIR_IN, "pwm0.pwm_ext_trg"},
    {0u, 6u, 15u, SOC_PINMUX_DIR_OUT, "pwm0.pwm_out0"},
    {0u, 7u, 1u, SOC_PINMUX_DIR_OUT, "pwm0.pwm_out1"},
    {0u, 7u, 2u, SOC_PINMUX_DIR_OUT, "pwm0.pwm_out2"},
    {0u, 7u, 3u, SOC_PINMUX_DIR_OUT, "pwm0.pwm_out3"},
    {0u, 7u, 4u, SOC_PINMUX_DIR_OUT, "pwm0.pwm_out_n0"},
    {0u, 7u, 5u, SOC_PINMUX_DIR_OUT, "pwm0.pwm_out_n1"},
    {0u, 7u, 6u, SOC_PINMUX_DIR_OUT, "pwm0.pwm_out_n2"},
    {0u, 7u, 7u, SOC_PINMUX_DIR_IN, "pwm1.pwm_break_in"},
    {0u, 7u, 8u, SOC_PINMUX_DIR_IN, "pwm1.pwm_break_in2"},
    {0u, 7u, 9u, SOC_PINMUX_DIR_IN, "pwm1.pwm_ext_clk"},
    {0u, 7u, 10u, SOC_PINMUX_DIR_IN, "pwm1.pwm_ext_trg"},
    {0u, 7u, 11u, SOC_PINMUX_DIR_OUT, "pwm1.pwm_out0"},
    {0u, 7u, 12u, SOC_PINMUX_DIR_OUT, "pwm1.pwm_out1"},
    {0u, 7u, 13u, SOC_PINMUX_DIR_OUT, "pwm1.pwm_out2"},
    {0u, 7u, 14u, SOC_PINMUX_DIR_OUT, "pwm1.pwm_out3"},
    {0u, 7u, 15u, SOC_PINMUX_DIR_OUT, "pwm1.pwm_out_n0"},
    {0u, 8u, 1u, SOC_PINMUX_DIR_OUT, "pwm1.pwm_out_n1"},
    {0u, 8u, 2u, SOC_PINMUX_DIR_OUT, "pwm1.pwm_out_n2"},
    {0u, 8u, 3u, SOC_PINMUX_DIR_OUT, "wwdt0.wwdt_reset"},
    {0u, 8u, 4u, SOC_PINMUX_DIR_IN, "rtc0.rtc_tamp1_i"},
    {0u, 8u, 5u, SOC_PINMUX_DIR_IN, "rtc0.rtc_tamp2_i"},
    {0u, 8u, 6u, SOC_PINMUX_DIR_IN, "rtc0.rtc_ts_i"},
    {0u, 8u, 7u, SOC_PINMUX_DIR_OUT, "rtc0.rtc_wkup_o"},
    {0u, 8u, 8u, SOC_PINMUX_DIR_OUT, "rtc0.rtc_alarm_o"},
    {0u, 8u, 9u, SOC_PINMUX_DIR_OUT, "rtc0.rtc_calib_o"},
};

uint32_t soc_pinmux_route_count(void) {
    return SOC_PINMUX_ROUTE_COUNT;
}

const soc_pinmux_route_t *soc_pinmux_route_table(void) {
    return g_soc_pinmux_routes;
}

int soc_pinmux_apply_route(uint32_t route_id) {
    const soc_pinmux_route_t *route;
    nc_gpio_dev_t *gpio;
    nc_status_t st;

    if (route_id >= SOC_PINMUX_ROUTE_COUNT) {
        return -1;
    }

    route = &g_soc_pinmux_routes[route_id];
    gpio = soc_get_gpio_dev((uint32_t)route->gpio_index);
    if (gpio == (nc_gpio_dev_t *)0) {
        return -1;
    }
    st = nc_gpio_set_mode(gpio, route->pin, NC_GPIO_MODE_AF);
    if (st != NC_OK) {
        return -1;
    }
    st = nc_gpio_set_af(gpio, route->pin, route->af);
    if (st != NC_OK) {
        return -1;
    }
    return 0;
}

int soc_pinmux_init_defaults(void) {
    if (soc_pinmux_apply_route(0u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(15u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(30u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(45u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(60u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(75u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(90u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(105u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(120u) != 0) {
        return -1;
    }
    return 0;
}

int soc_pinmux_enable_i2c0(void) {
    if (soc_pinmux_apply_route(16u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(17u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(18u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(19u) != 0) {
        return -1;
    }
    return 0;
}

int soc_pinmux_enable_i2c1(void) {
    if (soc_pinmux_apply_route(20u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(21u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(22u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(23u) != 0) {
        return -1;
    }
    return 0;
}

int soc_pinmux_enable_i2c2(void) {
    if (soc_pinmux_apply_route(24u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(25u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(26u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(27u) != 0) {
        return -1;
    }
    return 0;
}

int soc_pinmux_enable_pwm0(void) {
    if (soc_pinmux_apply_route(100u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(101u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(102u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(103u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(104u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(105u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(106u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(107u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(108u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(109u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(110u) != 0) {
        return -1;
    }
    return 0;
}

int soc_pinmux_enable_pwm1(void) {
    if (soc_pinmux_apply_route(111u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(112u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(113u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(114u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(115u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(116u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(117u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(118u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(119u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(120u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(121u) != 0) {
        return -1;
    }
    return 0;
}

int soc_pinmux_enable_rtc0(void) {
    if (soc_pinmux_apply_route(123u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(124u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(125u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(126u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(127u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(128u) != 0) {
        return -1;
    }
    return 0;
}

int soc_pinmux_enable_spi0(void) {
    if (soc_pinmux_apply_route(8u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(9u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(10u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(11u) != 0) {
        return -1;
    }
    return 0;
}

int soc_pinmux_enable_spi1(void) {
    if (soc_pinmux_apply_route(12u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(13u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(14u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(15u) != 0) {
        return -1;
    }
    return 0;
}

int soc_pinmux_enable_tmr0(void) {
    if (soc_pinmux_apply_route(28u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(29u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(30u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(31u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(32u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(33u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(34u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(35u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(36u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(37u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(38u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(39u) != 0) {
        return -1;
    }
    return 0;
}

int soc_pinmux_enable_tmr1(void) {
    if (soc_pinmux_apply_route(40u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(41u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(42u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(43u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(44u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(45u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(46u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(47u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(48u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(49u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(50u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(51u) != 0) {
        return -1;
    }
    return 0;
}

int soc_pinmux_enable_tmr2(void) {
    if (soc_pinmux_apply_route(52u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(53u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(54u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(55u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(56u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(57u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(58u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(59u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(60u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(61u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(62u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(63u) != 0) {
        return -1;
    }
    return 0;
}

int soc_pinmux_enable_tmr3(void) {
    if (soc_pinmux_apply_route(64u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(65u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(66u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(67u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(68u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(69u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(70u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(71u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(72u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(73u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(74u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(75u) != 0) {
        return -1;
    }
    return 0;
}

int soc_pinmux_enable_tmr4(void) {
    if (soc_pinmux_apply_route(76u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(77u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(78u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(79u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(80u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(81u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(82u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(83u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(84u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(85u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(86u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(87u) != 0) {
        return -1;
    }
    return 0;
}

int soc_pinmux_enable_tmr5(void) {
    if (soc_pinmux_apply_route(88u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(89u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(90u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(91u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(92u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(93u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(94u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(95u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(96u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(97u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(98u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(99u) != 0) {
        return -1;
    }
    return 0;
}

int soc_pinmux_enable_uart0(void) {
    if (soc_pinmux_apply_route(0u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(1u) != 0) {
        return -1;
    }
    return 0;
}

int soc_pinmux_enable_uart1(void) {
    if (soc_pinmux_apply_route(2u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(3u) != 0) {
        return -1;
    }
    return 0;
}

int soc_pinmux_enable_uart2(void) {
    if (soc_pinmux_apply_route(4u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(5u) != 0) {
        return -1;
    }
    return 0;
}

int soc_pinmux_enable_uart3(void) {
    if (soc_pinmux_apply_route(6u) != 0) {
        return -1;
    }
    if (soc_pinmux_apply_route(7u) != 0) {
        return -1;
    }
    return 0;
}

int soc_pinmux_enable_wwdt0(void) {
    if (soc_pinmux_apply_route(122u) != 0) {
        return -1;
    }
    return 0;
}
