/*
 * Copyright (c) 2026 NC Factory
 * Author: NC MCU Factory Requirements Agent
 * License: Apache-2.0
 * Generated by: nc_socgen/scripts/gen_soc.py
 * Generator version: 1.1.0
 * Generation UTC: 2026-05-29T04:57:53.077343+00:00
 * Source config: /tmp/soc_config_gen.yaml
 * NOTE: Auto-generated file. Do not edit manually.
 */

#include "soc_board.h"

static nc_gpio_dev_t g_gpio0;
static nc_gpio_dev_t g_gpio1;
static nc_gpio_dev_t g_gpio2;
static nc_uart_dev_t g_uart0;
static nc_uart_dev_t g_uart1;
static nc_uart_dev_t g_uart2;
static nc_uart_dev_t g_uart3;
static nc_spi_dev_t g_spi0;
static nc_spi_dev_t g_spi1;
static nc_i2c_dev_t g_i2c0;
static nc_i2c_dev_t g_i2c1;
static nc_i2c_dev_t g_i2c2;
static nc_tmr_dev_t g_tmr0;
static nc_tmr_dev_t g_tmr1;
static nc_tmr_dev_t g_tmr2;
static nc_tmr_dev_t g_tmr3;
static nc_tmr_dev_t g_tmr4;
static nc_tmr_dev_t g_tmr5;
static nc_pwm_dev_t g_pwm0;
static nc_pwm_dev_t g_pwm1;
static nc_dmac_dev_t g_dmac0;
static nc_crc_dev_t g_crc0;
static nc_aes_dev_t g_aes0;
static nc_wwdt_dev_t g_wwdt0;
static nc_rtc_dev_t g_rtc0;
static nc_systick_dev_t g_systick0;
static nc_xip_dev_t g_xip0;

int soc_drivers_init(void) {
    nc_status_t st;
    st = nc_gpio_init(&g_gpio0, (uintptr_t)SOC_GPIO0_BASE, NULL);
    if (st != NC_OK) {
        return -1;
    }
    st = nc_gpio_init(&g_gpio1, (uintptr_t)SOC_GPIO1_BASE, NULL);
    if (st != NC_OK) {
        return -1;
    }
    st = nc_gpio_init(&g_gpio2, (uintptr_t)SOC_GPIO2_BASE, NULL);
    if (st != NC_OK) {
        return -1;
    }
    st = nc_uart_init(&g_uart0, (uintptr_t)SOC_UART0_BASE, NULL);
    if (st != NC_OK) {
        return -1;
    }
    st = nc_uart_init(&g_uart1, (uintptr_t)SOC_UART1_BASE, NULL);
    if (st != NC_OK) {
        return -1;
    }
    st = nc_uart_init(&g_uart2, (uintptr_t)SOC_UART2_BASE, NULL);
    if (st != NC_OK) {
        return -1;
    }
    st = nc_uart_init(&g_uart3, (uintptr_t)SOC_UART3_BASE, NULL);
    if (st != NC_OK) {
        return -1;
    }
    st = nc_spi_init(&g_spi0, (uintptr_t)SOC_SPI0_BASE, NULL);
    if (st != NC_OK) {
        return -1;
    }
    st = nc_spi_init(&g_spi1, (uintptr_t)SOC_SPI1_BASE, NULL);
    if (st != NC_OK) {
        return -1;
    }
    st = nc_i2c_init(&g_i2c0, (uintptr_t)SOC_I2C0_BASE, NULL);
    if (st != NC_OK) {
        return -1;
    }
    st = nc_i2c_init(&g_i2c1, (uintptr_t)SOC_I2C1_BASE, NULL);
    if (st != NC_OK) {
        return -1;
    }
    st = nc_i2c_init(&g_i2c2, (uintptr_t)SOC_I2C2_BASE, NULL);
    if (st != NC_OK) {
        return -1;
    }
    st = nc_tmr_init(&g_tmr0, (uintptr_t)SOC_TMR0_BASE, NULL);
    if (st != NC_OK) {
        return -1;
    }
    st = nc_tmr_init(&g_tmr1, (uintptr_t)SOC_TMR1_BASE, NULL);
    if (st != NC_OK) {
        return -1;
    }
    st = nc_tmr_init(&g_tmr2, (uintptr_t)SOC_TMR2_BASE, NULL);
    if (st != NC_OK) {
        return -1;
    }
    st = nc_tmr_init(&g_tmr3, (uintptr_t)SOC_TMR3_BASE, NULL);
    if (st != NC_OK) {
        return -1;
    }
    st = nc_tmr_init(&g_tmr4, (uintptr_t)SOC_TMR4_BASE, NULL);
    if (st != NC_OK) {
        return -1;
    }
    st = nc_tmr_init(&g_tmr5, (uintptr_t)SOC_TMR5_BASE, NULL);
    if (st != NC_OK) {
        return -1;
    }
    st = nc_pwm_init(&g_pwm0, (uintptr_t)SOC_PWM0_BASE, NULL);
    if (st != NC_OK) {
        return -1;
    }
    st = nc_pwm_init(&g_pwm1, (uintptr_t)SOC_PWM1_BASE, NULL);
    if (st != NC_OK) {
        return -1;
    }
    st = nc_dmac_init(&g_dmac0, (uintptr_t)SOC_DMAC0_BASE, NULL);
    if (st != NC_OK) {
        return -1;
    }
    st = nc_crc_init(&g_crc0, (uintptr_t)SOC_CRC0_BASE, NULL);
    if (st != NC_OK) {
        return -1;
    }
    st = nc_aes_init(&g_aes0, (uintptr_t)SOC_AES0_BASE, NULL);
    if (st != NC_OK) {
        return -1;
    }
    st = nc_wwdt_init(&g_wwdt0, (uintptr_t)SOC_WWDT0_BASE, NULL);
    if (st != NC_OK) {
        return -1;
    }
    st = nc_rtc_init(&g_rtc0, (uintptr_t)SOC_RTC0_BASE, NULL);
    if (st != NC_OK) {
        return -1;
    }
    st = nc_systick_init(&g_systick0, (uintptr_t)SOC_SYSTICK0_BASE, NULL);
    if (st != NC_OK) {
        return -1;
    }
    /* XIP window is mapped at 0x00000000 for this profile; skip nc_xip_init. */
    return 0;
}

uint32_t soc_gpio_count(void) {
    return 3u;
}

nc_gpio_dev_t *soc_get_gpio_dev(uint32_t index) {
    switch (index) {
    case 0u: return &g_gpio0;
    case 1u: return &g_gpio1;
    case 2u: return &g_gpio2;
    default: return (nc_gpio_dev_t *)0;
    }
}
