/*
 * Copyright (c) 2026 NC Factory
 * Author: NC MCU Factory Requirements Agent
 * License: Apache-2.0
 * Generated by: nc_socgen/scripts/gen_soc.py
 * Generator version: 1.1.0
 * Generation UTC: 2026-05-29T04:57:53.077343+00:00
 * Source config: /tmp/soc_config_gen.yaml
 * NOTE: Auto-generated file. Do not edit manually.
 */

#include <stdint.h>
#include "soc_board.h"
#include "soc_pinmux.h"

#define TEST_PASS (0x00000001u)
#define TEST_FAIL (0xDEAD0001u)

static void write_status(uint32_t code) {
    volatile uint32_t *status = (volatile uint32_t *)0x20000000u;
    *status = code;
}

int main(void) {
#ifdef SOC_FW_BOOT_FAST
    // Fast FW boot mode used by simulation regressions.
    write_status(TEST_PASS);
    for (;;) { }
#else
    if (soc_drivers_init() != 0) {
        write_status(TEST_FAIL);
        for (;;) { }
    }
    if (soc_pinmux_init_defaults() != 0) {
        write_status(TEST_FAIL);
        for (;;) { }
    }
    // No ID-register checks found in register YAML. Basic driver init is used as smoke.
    write_status(TEST_PASS);
    for (;;) { }
#endif
}
